version: '2.2'
services:
  insights-tag-db:
    image: registry.access.redhat.com/rhscl/postgresql-96-rhel7
    ports:
      - 5746:5432
    environment:
      - POSTGRESQL_DATABASE=tagservice
      - POSTGRESQL_USER=tagservice
      - POSTGRESQL_PASSWORD=tagservice
    command: sh -c "mkdir -p /opt/app-root/src/postgresql-start &&
                    echo 'psql -c \"ALTER USER tagservice CREATEDB;\"' >> /opt/app-root/src/postgresql-start/make_test_work.sh &&
                    run-postgresql"

  insights-tag-api:
    build: .
    ports:
      - 8746:8746
    environment:
      - DB_HOST=insights-tag-db
      - DB_PORT=5746
      - LOG_LEVEL=INFO
    depends_on:
      - insights-tag-db
    command: sh -c "./app.sh"
