swagger: '2.0'
info:
  title: Insights Platform Tag API
  description: A REST API to manage tags in the Insights Platform.
  version: v1
basePath: /v1
consumes:
  - application/json
produces:
  - application/json
paths:
  /tags:
    get:
      description: ''
      responses:
        '200':
          description: 'List tags response'
          schema:
            required:
              - count
              - results
            type: object
            properties:
              count:
                type: integer
              results:
                type: array
                items:
                  $ref: '#/definitions/NamespaceRetrieve'
      tags:
        - tags
    post:
      description: ''
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/TagPost'
      responses:
        '201':
          description: 'Created tag successfully response'
          schema:
            $ref: '#/definitions/TagRetrieve'
      tags:
        - tags
    parameters: []
  /tags/{id}:
    get:
      description: ''
      parameters: []
      responses:
        '200':
          description: 'Get single tag successful response'
          schema:
            $ref: '#/definitions/TagRetrieve'
        '404':
            $ref: '#/responses/NotFound'
      tags:
        - tags
    put:
      description: ''
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/TagPut'
      responses:
        '200':
          description: 'PUT tag successful response'
          schema:
            $ref: '#/definitions/TagRetrieve'
        '404':
            $ref: '#/responses/NotFound'
      tags:
        - tags
    patch:
      description: ''
      parameters:
        - name: body
          in: body
          required: false
          schema:
            $ref: '#/definitions/TagPatch'
      responses:
        '200':
          description: 'PATCH tag successful response'
          schema:
            $ref: '#/definitions/TagRetrieve'
        '404':
            $ref: '#/responses/NotFound'
      tags:
        - tags
    parameters:
      - name: id
        in: path
        description: A unique value identifying this tag.
        required: true
        type: string
responses:
  NotFound:
    description: The specified resource was not found
    schema:
      $ref: '#/definitions/Error'
definitions:
  Error:
    type: object
    properties:
      message:
        type: string
    required:
      - message
  TagPut:
    required:
      - id
      - name
      - value
      - description
      - account_id
      - namespace
    type: object
    properties:
      id:
        title: ID
        type: string
        minLength: 1
      name:
        title: Name
        type: string
        minLength: 1
      description:
        title: Description
        type: string
        minLength: 1
      value:
        title: Value
        type: string
      account_id:
        title: Account ID
        type: string
      namespace:
        title: Namespace
        type: string
  TagPatch:
    type: object
    properties:
      name:
        title: Name
        type: string
        minLength: 1
      description:
        title: Description
        type: string
        minLength: 1
      value:
        title: Value
        type: string
  TagPost:
    required:
      - name
      - description
      - account_id
      - value
      - namespace
    type: object
    properties:
      name:
        title: Name
        type: string
        minLength: 1
      description:
        title: Description
        type: string
        minLength: 1
      value:
        title: Value
        type: string
      account_id:
        title: Account ID
        type: string
      namespace:
        title: Namespace
        type: string
  NamespaceRetrieve:
    required:
      - name
      - tags
    type: object
    properties:
      name:
        title: Name
        type: string
      tags:
        title: Tags
        type: array
        items:
          type: object
  TagRetrieve:
    required:
      - id
      - name
      - value
      - description
      - account_id
      - namespace
      - created_at
      - updated_at
    type: object
    properties:
      id:
        title: Id
        type: string
        minLength: 1
      name:
        title: Name
        type: string
        minLength: 1
      description:
        title: Description
        type: string
        minLength: 1
      value:
        title: Value
        type: string
      account_id:
        title: Account ID
        type: string
      namespace:
        title: Namespace
        type: string
      created_at:
        title: Created at
        type: string
        format: date-time
        readOnly: true
      updated_at:
        title: Updated at
        type: string
        format: date-time
        readOnly: true
